site_name: PizzaTime's Bean Collection
repo_url: https://github.com/ItsPizzaTime1501/ItsPizzaTime1501.github.io
theme:
    name: darkly
    # default from mkdocs_theme.yml
    static_templates:
        - 404.html
    include_search_page: true
    search_index_only: false
    history_buttons: true
    article_nav_top: true
    article_nav_bottom: true

nav:
    - 'Home' : 'index.md'
    - 'Guides' :
        - 'Installing Themes' : 'guides/themes.md'
        - 'Plugins' : 'guides/plugins.md'
        - 'Flashcart Widescreen' : 'guides/flashcart_widescreen.md'
    - 'Downloads' : 'downloads.md'
